### ISSUE TITLE
Dados do Profissional Bloco Home

### ISSUE THREAD

**Issue by demetriuscaminha** [demetriuscaminha/guiapsi#2]
No Bloco de Profissionais da Home, podemos trazer mais algumas informações.
Sugestão: Nome (já existente), Descrição (já existente), localização (ver no mapa), telefones para contato, tipo de atendimento (crianças, adultos, etc...)

**Comment by alefcastelo** [comment]
No caso de "tipo de atendimento (crianças, adultos, etc...)" não tem como definir pois esses campos teoricamente não existe, ele na verdade é um field collection e o profissional vai decidir se quer ou não preencher essa informação

**Comment by demetriuscaminha** [comment]
Alef, esse tipo de informação é imprescindível para os profissionais desta área. essa informação tem que ser obrigatória.
