### ISSUE TITLE
Filtro de Profissionais (Home Page)

### ISSUE THREAD

**Issue by demetriuscaminha** [demetriuscaminha/guiapsi#3]
1. Elaborar melhor o título do bloco.
2. Modificar o texto do botão de envio do filtro.
3. Preparar os "selects" para receber estilo personalizado.

**Comment by alefcastelo** [comment]
Preparar os "selects" para receber estilo personalizado, vai custa um pouco pq preciso sincronizar os eventos entre os selects e o plugin!
