### ISSUE TITLE
Rodapé

### ISSUE THREAD

**Issue by demetriuscaminha** [demetriuscaminha/guiapsi#7]
1. Inserir no rodapé um bloco com uma lista de algumas especialidades (serão exibidas de forma aleatória).
   Essa listagem será exibida em um formato semelhante a nuvem de tags.
2. Inserir também uma outra listagem com os últimos profissionais inscritos, como forma de promovê-los.
3. Inserir as redes sociais com o font awsome.

Ver estrutura no Mundo dos Psicologos.
Esta pode ser a ordem de inserção dos blocos.

**Comment by alefcastelo** [comment]
O modulo tagadelic está com bug, estou pensando em troca por uma views!

**Comment by demetriuscaminha** [comment]
Não é preciso usar nenhum módulo. Podemos usar views mesmo. É um bloco listando os profissionais por ordem decrescente de cadastro.
