### ISSUE TITLE
Pesquisa no topo do site

### ISSUE THREAD

**Issue by demetriuscaminha** [demetriuscaminha/guiapsi#8]
Inserir a pesquisa no mesmo bloco em que se encontra a logo.
Lá foi criada uma região para facilitar a inserção de conteúdo nesta área.

Não esquecer das permissões para usuário anônimo na pesquisa e de configurar corretamente a saída da pesquisa (pelo que tenho visto, é bem melhor criar uma view pra essa exibição dos resultados, pois esse conteúdo fica melhor estruturado).

**Comment by alefcastelo** [comment]
pronto
